linters-settings:
  gocyclo:
    min-complexity: 20
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nestif
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - bodyclose
    - structcheck

run:
  timeout: 5m
  go: "1.17"
