apiVersion: database.cockroachdb.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: cluster
spec:
  forProvider:
    provider: AWS
    regions:
      - eu-west-1
    spendLimit: 0
  providerConfigRef:
    name: default
