apiVersion: database.cockroachdb.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: cluster
spec:
  forProvider:
    provider: AWS
    serverless:
      regions:
        - eu-west-1
      spendLimit: 0
    credentials:
      username: cluster
      # A random password will be generated if not provided
      # passwordSecretRef:
      #   name: cluster-password
      #   namespace: default
      #   key: password
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: default
  providerConfigRef:
    name: default
