apiVersion: cockroachdb.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: cockroachdb-provider-secret
      key: credentials
